### ISSUE TITLE
TypeError: The "options.context" property must be an vm.Context. Received an instance of Object

### ISSUE THREAD

**Issue by TheLonelyAdventurer** [kayahr/jest-environment-node-single-context#10]
I'm using Yarn 3 with pnp modules.

When I try to run Jest tests, it fails with:

```
  ● Test suite failed to run

    TypeError: The "options.context" property must be an vm.Context. Received an instance of Object

      at Runtime.loadEsmModule (.yarn/cache/jest-runtime-npm-28.1.0-111844adc0-e3a01bbbf6.zip/node_modules/jest-runtime/build/index.js:607:24)
```

I think it is related to Yarn, but I am not sure whether this is a bug of Yarn itself.

The command I use for running tests is:

```shell
yarn node --experimental-vm-modules $(yarn bin jest) --verbose --maxWorkers=1
```

**Comment by kayahr** [comment]
This is very helpful thanks. I'll take a look but can't promise anything. This project is just a hack to circumvent a broken Jest feature and if this hack doesn't work with ESM for some reason then maybe a completely different hack is needed...

**Comment by TheLonelyAdventurer** [comment]
> This is very helpful thanks. I'll take a look but can't promise anything. This project is just a hack to circumvent a broken Jest feature and if this hack doesn't work with ESM for some reason then maybe a completely different hack is needed...

I'm guessing there are multiple separated issues with Jest and Node involved here... Sadly all I know is that the running context plays a fundamental role in module resolution.

**Comment by xenova** [comment]
I just ran into this issue too. @TheLonelyAdventurer where you able to figure out a workaround?

**Comment by TheLonelyAdventurer** [comment]
> I just ran into this issue too. @TheLonelyAdventurer were you able to figure out a workaround?

I don't remember specifically, but the setup I used in https://github.com/Squirrel-Network/esbuild-sass-modules-plugin worked well for me.

**Comment by kayahr** [comment]
Found some time to dig into it. So when Jest is used with CommonJS then the context provided by the test environment is just used to call `script.runInContext` which is the target of the ugly hack I use in this project to redirect these calls to `script.runInThisContext`. 

But when ESM is used then Jest goes a completely different route and uses the context of the test environment for other stuff. And because I return a faked context there Jest fails...

I reworked the ugly hack a little bit so now a real context is returned. This doesn't affect Jest with CommonJS because the hack still redirects to the current context but ESM Jest now uses this context so the error should be fixed. But unfortunately this means that Jest uses a new context again which is exactly what this special environment should prevent. But at least the new context is created with the shared global scope as argument which is not the case when using the standard node test environment. This means most of the global types work correctly but unfortunately not all. Maybe it is enough to be useful, though... 

You can try it out with new version v29.4.0.

Or maybe give [jest-light-runner](https://www.npmjs.com/package/jest-light-runner) a try which looks like a much cleaner solution than my hacky environment implementation.
